workflow:
  rules:
    # Run pipeline for merge requests
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: always

    # Run pipeline for pushes only if there is no MR
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_OPEN_MERGE_REQUESTS == null'
      when: always

    # In all other cases, don't run a pipeline
    - when: never

image: docker:latest

variables:
  RUNNER_TAG:
    value: "amd64"
    description: 'Runner tag.'
  E:
    value: ""
    description: 'Prefix to all commands (set to "echo" for dry running).'

default:
  tags:
    - $RUNNER_TAG

services:
  - name: docker:dind

stages:
  - tests

# .test-base: Reusable block for building and testing Aktualizr inside a container.
#
# Required input variables:
# - DOCKER_IMG: name of the Docker image to build without the tag
# - DOCKER_TAG: tag to assign the image (an extra suffix will be added)
# - DOCKERFILE: Dockerfile that will produce the image
#
.test-base:
  stage: tests
  before_script:
    - '[ -n "${DOCKER_IMG}" ] || { echo "Variable DOCKER_IMG must be set"; false; }'
    - '[ -n "${DOCKER_TAG}" ] || { echo "Variable DOCKER_TAG must be set"; false; }'
    - '[ -n "${DOCKERFILE}" ] || { echo "Variable DOCKERFILE must be set"; false; }'

    - echo -e "\e[0Ksection_start:$(date +%s):pull_submodules\r\e[0KFetch Aktualizr submodules"
    - ${E} apk update
    - ${E} apk add git ca-certificates
    - ${E} git submodule update --init --recursive
    - echo -e "\e[0Ksection_end:$(date +%s):pull_submodules\r\e[0K"

    - echo -e "\e[0Ksection_start:$(date +%s):build_container\r\e[0KBuild test container"
    - ${E} docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
    - suf=${CI_MERGE_REQUEST_TARGET_BRANCH_NAME}
    - suf=${suf:-${CI_COMMIT_BRANCH}}
    - suf=${suf?Could not determine tag suffix}
    - tag="${CI_REGISTRY_IMAGE}/${DOCKER_IMG}:${DOCKER_TAG}-${suf}"
    # Reference: https://docs.gitlab.com/ci/docker/docker_layer_caching/
    - ${E} docker pull "${tag}" || true
    - ${E} docker build --build-arg BUILDKIT_INLINE_CACHE=1
                        --cache-from "${tag}" --tag "${tag}" -f "${DOCKERFILE}" .
    - echo -e "\e[0Ksection_end:$(date +%s):build_container\r\e[0K"

    - echo -e "\e[0Ksection_start:$(date +%s):update_registry\r\e[0KUpdate Docker cache"
    - ${E} docker push "${tag}"
    - echo -e "\e[0Ksection_end:$(date +%s):update_registry\r\e[0K"

    # Helpers to run commands inside the test container (available in the "script" section).
    - |
      docker_run() {
          ${E} docker run \
               --mount="type=volume,source=build-vol,destination=/home/testuser/build" \
               --mount="type=volume,source=cache-vol,destination=/home/testuser/.cache" \
               --rm -i "${tag}" "$@"
      }
      docker_cmd() {
          docker_run bash -c "$@"
      }

    # Helpers to restore/save ccache
    - |
      restore_ccache() {
          docker_run tar -xf- < "${CI_PROJECT_DIR}/${1?missing tarball name}" || echo "No cache found"
          docker_run ccache --zero-stats
      }
      save_ccache() {
          docker_run ccache --show-stats
          docker_run tar -cf- ".cache" > "${CI_PROJECT_DIR}/${1?missing tarball name}"
      }

# NOTES:
#
# - We do not run check-format on bullseye; the "right" format will be defined by the checks
#   performed on Debian bookworm.
#
# - We build, run tests and clang-tidy on both Debian bullseye and bookworm such that we'll always
#   try to keep Aktualizr building free of warnings and running correctly on both environments.
#
test-bullseye-p11:
  extends: .test-base
  variables:
    DOCKER_IMG: aktualizr-ci
    DOCKER_TAG: bullseye
    DOCKERFILE: docker/Dockerfile.debian.bullseye
    TEST_SCRIPT: source/scripts/build-and-test-bullseye.sh
    # TODO: Fix the errors with these tests.
    TEST_BLACKLIST: >-
      test_aktualizr
      test_aktualizr_update_lock
      test_c_api
      test_command_runner
      test_customrepo_failure
      test_install_aktualizr_and_update
      test_ip_secondary
      test_ip_secondary_ostree
      test_ip_secondary_rotation
      test_misc_ostree_update
      test_ostree_custom_uri
      test_treehub_failure
      test_uptane
      test_uptane_cancellation
      test_uptane_delegation
      test_uptane_network
      test_uptane_update_failure
    CCACHE_TAR: cache-bullseye.tar
  cache:
    key: "${CI_COMMIT_REF_SLUG}"
    paths:
      - "${CCACHE_TAR}"
  script:
    - restore_ccache "${CCACHE_TAR}"

    - echo -e "\e[0Ksection_start:$(date +%s):gen_buildsys\r\e[0KGenerate build-system files"
    - docker_cmd "STEPS='gen-buildsys' ${TEST_SCRIPT}"
    - echo -e "\e[0Ksection_end:$(date +%s):gen_buildsys\r\e[0K"

    - echo -e "\e[0Ksection_start:$(date +%s):build_aktualizr\r\e[0KBuild Aktualizr"
    - docker_cmd "STEPS='build-default' ${TEST_SCRIPT}"
    - echo -e "\e[0Ksection_end:$(date +%s):build_aktualizr\r\e[0K"

    - echo -e "\e[0Ksection_start:$(date +%s):build_tests\r\e[0KBuild tests"
    - docker_cmd "STEPS='build-tests' ${TEST_SCRIPT}"
    - echo -e "\e[0Ksection_end:$(date +%s):build_tests\r\e[0K"

    - save_ccache "${CCACHE_TAR}"

    - echo -e "\e[0Ksection_start:$(date +%s):run_tests\r\e[0KRun tests"
    - docker_cmd "STEPS='run-tests' TEST_BLACKLIST=\"${TEST_BLACKLIST}\" CTEST_PARALLEL_LEVEL=$(nproc) CTEST_OUTPUT_ON_FAILURE=1 ${TEST_SCRIPT}"
    - echo -e "\e[0Ksection_end:$(date +%s):run_tests\r\e[0K"

test-bookworm-nop11:
  extends: .test-base
  variables:
    DOCKER_IMG: aktualizr-ci
    DOCKER_TAG: bookworm
    DOCKERFILE: docker/Dockerfile.debian.bookworm
    TEST_SCRIPT: source/scripts/build-and-test-bookworm.sh
    TEST_BLACKLIST: >-
      aktualizr-option-version
      test-help-with-nonexistent-options
      test-help-with-other-options
      test_aktualizr
      test_aktualizr_update_lock
      test_c_api
      test_customrepo_failure
      test_install_aktualizr_and_update
      test_ip_secondary
      test_ip_secondary_rotation
      test_uptane
      test_uptane_cancellation
      test_uptane_delegation
      test_uptane_network
      test_uptane_update_failure
    CCACHE_TAR: cache-bookworm.tar
  script:
    - restore_ccache "${CCACHE_TAR}"

    - echo -e "\e[0Ksection_start:$(date +%s):gen_buildsys\r\e[0KGenerate build-system files"
    - docker_cmd "STEPS='gen-buildsys' ${TEST_SCRIPT}"
    - echo -e "\e[0Ksection_end:$(date +%s):gen_buildsys\r\e[0K"

    - echo -e "\e[0Ksection_start:$(date +%s):build_aktualizr\r\e[0KBuild Aktualizr and Tests"
    - docker_cmd "STEPS='build-tests' ${TEST_SCRIPT}"
    - echo -e "\e[0Ksection_end:$(date +%s):build_aktualizr\r\e[0K"

    - save_ccache "${CCACHE_TAR}"

    - echo -e "\e[0Ksection_start:$(date +%s):run_tests\r\e[0KRun tests"
    - docker_cmd "STEPS='run-tests' TEST_BLACKLIST=\"${TEST_BLACKLIST}\" CTEST_PARALLEL_LEVEL=$(nproc) CTEST_OUTPUT_ON_FAILURE=1 ${TEST_SCRIPT}"
    - echo -e "\e[0Ksection_end:$(date +%s):run_tests\r\e[0K"

test-trixie-nop11:
  extends: .test-base
  variables:
    DOCKER_IMG: aktualizr-ci
    DOCKER_TAG: trixie
    DOCKERFILE: docker/Dockerfile.debian.trixie
    TEST_SCRIPT: source/scripts/build-and-test-trixie.sh
    TEST_BLACKLIST: >-
      aktualizr-option-version
      test-help-with-nonexistent-options
      test-help-with-other-options
      test_aktualizr
      test_aktualizr_update_lock
      test_c_api
      test_customrepo_failure
      test_install_aktualizr_and_update
      test_ip_secondary
      test_ip_secondary_rotation
      test_uptane
      test_uptane_cancellation
      test_uptane_delegation
      test_uptane_network
      test_uptane_update_failure
    CCACHE_TAR: cache-trixie.tar
  script:
    - restore_ccache "${CCACHE_TAR}"

    - echo -e "\e[0Ksection_start:$(date +%s):gen_buildsys\r\e[0KGenerate build-system files"
    - docker_cmd "STEPS='gen-buildsys' ${TEST_SCRIPT}"
    - echo -e "\e[0Ksection_end:$(date +%s):gen_buildsys\r\e[0K"

    - echo -e "\e[0Ksection_start:$(date +%s):check_format\r\e[0KCheck format"
    - docker_cmd "STEPS='check-format' ${TEST_SCRIPT}"
    - echo -e "\e[0Ksection_end:$(date +%s):check_format\r\e[0K"

    - echo -e "\e[0Ksection_start:$(date +%s):build_aktualizr\r\e[0KBuild Aktualizr"
    - docker_cmd "STEPS='build-default' ${TEST_SCRIPT}"
    - echo -e "\e[0Ksection_end:$(date +%s):build_aktualizr\r\e[0K"

    - echo -e "\e[0Ksection_start:$(date +%s):build_tests\r\e[0KBuild tests"
    - docker_cmd "STEPS='build-tests' ${TEST_SCRIPT}"
    - echo -e "\e[0Ksection_end:$(date +%s):build_tests\r\e[0K"

    - save_ccache "${CCACHE_TAR}"

    - echo -e "\e[0Ksection_start:$(date +%s):run_tests\r\e[0KRun tests"
    - docker_cmd "STEPS='run-tests' TEST_BLACKLIST=\"${TEST_BLACKLIST}\" CTEST_PARALLEL_LEVEL=$(nproc) CTEST_OUTPUT_ON_FAILURE=1 ${TEST_SCRIPT}"
    - echo -e "\e[0Ksection_end:$(date +%s):run_tests\r\e[0K"

    - echo -e "\e[0Ksection_start:$(date +%s):clang_tidy\r\e[0KRun clang-tidy"
    - docker_cmd "STEPS='tidy' ${TEST_SCRIPT}"
    - echo -e "\e[0Ksection_end:$(date +%s):clang_tidy\r\e[0K"

# Currently running shellcheck via the bullseye container
shellcheck:
  extends: .test-base
  variables:
    DOCKER_IMG: aktualizr-ci
    DOCKER_TAG: bullseye-shellcheck
    DOCKERFILE: docker/Dockerfile.debian.bullseye
  script:
    - echo -e "\e[0Ksection_start:$(date +%s):run_shellcheck\r\e[0KShellcheck"
    - docker_cmd "find source/ \( -name third_party -prune \) -o -name \*.sh -exec shellcheck -fgcc {} \+"
    - echo -e "\e[0Ksection_end:$(date +%s):run_shellcheck\r\e[0K"

# TODO: Consider adding a new job similar to "static-check" (upstream)
# TODO: Consider using clang-tidy-diff.py to only run clang-tidy on changed files
